version: 2.1

jobs:
  test:
    working_directory: ~/app
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run: yarn install --immutable --immutable-cache
      - run: yarn check:deps
      - run: yarn check:lint
      - run: yarn check:pretty

workflows:
  version: 2

  workflow:
    jobs:
      - test
