name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --immutable --immutable-cache
      - run: yarn check:deps
      - run: yarn check:lint
      - run: yarn check:pretty
      - run: yarn check:css
